"""fundament: uzytkownik (allowlista), dziennik zdarzen, numeracja dokumentow

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 08:04:47.070342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seria_numeracji',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('kod', sa.String(length=30), nullable=False),
    sa.Column('typ_dokumentu', sa.String(length=30), nullable=False),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.Column('wzorzec', sa.String(length=60), nullable=False),
    sa.Column('okres_resetu', sa.String(length=10), nullable=False),
    sa.Column('aktywna', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('utworzono', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("okres_resetu IN ('miesiac', 'rok', 'brak')", name=op.f('ck_seria_numeracji_okres_resetu')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seria_numeracji')),
    sa.UniqueConstraint('kod', name=op.f('uq_seria_numeracji_kod'))
    )
    op.create_table('uzytkownik',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('imie', sa.String(length=100), server_default='', nullable=False),
    sa.Column('rola', sa.String(length=20), server_default='uzytkownik', nullable=False),
    sa.Column('aktywny', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('utworzono', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ostatnie_logowanie', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("rola IN ('admin', 'uzytkownik')", name=op.f('ck_uzytkownik_rola')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_uzytkownik_email_male_litery')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uzytkownik')),
    sa.UniqueConstraint('email', name=op.f('uq_uzytkownik_email'))
    )
    op.create_table('dziennik_zdarzen',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('czas', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uzytkownik_id', sa.BigInteger(), nullable=True),
    sa.Column('akcja', sa.String(length=60), nullable=False),
    sa.Column('encja', sa.String(length=60), nullable=True),
    sa.Column('encja_id', sa.BigInteger(), nullable=True),
    sa.Column('przed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('po', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uzytkownik_id'], ['uzytkownik.id'], name=op.f('fk_dziennik_zdarzen_uzytkownik_id_uzytkownik'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dziennik_zdarzen'))
    )
    op.create_index(op.f('ix_dziennik_zdarzen_akcja'), 'dziennik_zdarzen', ['akcja'], unique=False)
    op.create_index(op.f('ix_dziennik_zdarzen_uzytkownik_id'), 'dziennik_zdarzen', ['uzytkownik_id'], unique=False)
    op.create_table('licznik_numeracji',
    sa.Column('seria_id', sa.BigInteger(), nullable=False),
    sa.Column('okres', sa.String(length=7), nullable=False),
    sa.Column('ostatni_numer', sa.Integer(), nullable=False),
    sa.CheckConstraint('ostatni_numer >= 0', name=op.f('ck_licznik_numeracji_nieujemny')),
    sa.ForeignKeyConstraint(['seria_id'], ['seria_numeracji.id'], name=op.f('fk_licznik_numeracji_seria_id_seria_numeracji'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('seria_id', 'okres', name=op.f('pk_licznik_numeracji'))
    )
    # ### end Alembic commands ###

    # Dziennik zdarzen tylko do dopisywania (niezmiennik, pkt 5). Blokada w bazie, a nie
    # tylko w kodzie: zaden blad aplikacji ani reczne zapytanie nie przepisze historii.
    op.execute("""
        CREATE FUNCTION dziennik_zdarzen_tylko_dopisywanie() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'dziennik_zdarzen: % zabroniony - dziennik jest tylko do dopisywania', TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER dziennik_zdarzen_bez_zmian
        BEFORE UPDATE OR DELETE ON dziennik_zdarzen
        FOR EACH ROW EXECUTE FUNCTION dziennik_zdarzen_tylko_dopisywanie()
    """)
    op.execute("""
        CREATE TRIGGER dziennik_zdarzen_bez_truncate
        BEFORE TRUNCATE ON dziennik_zdarzen
        FOR EACH STATEMENT EXECUTE FUNCTION dziennik_zdarzen_tylko_dopisywanie()
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS dziennik_zdarzen_bez_truncate ON dziennik_zdarzen")
    op.execute("DROP TRIGGER IF EXISTS dziennik_zdarzen_bez_zmian ON dziennik_zdarzen")
    op.execute("DROP FUNCTION IF EXISTS dziennik_zdarzen_tylko_dopisywanie()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licznik_numeracji')
    op.drop_index(op.f('ix_dziennik_zdarzen_uzytkownik_id'), table_name='dziennik_zdarzen')
    op.drop_index(op.f('ix_dziennik_zdarzen_akcja'), table_name='dziennik_zdarzen')
    op.drop_table('dziennik_zdarzen')
    op.drop_table('uzytkownik')
    op.drop_table('seria_numeracji')
    # ### end Alembic commands ###
