"""uwagi: lista poprawek i pomyslow do aplikacji

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 20:04:54.668448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uwaga',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tresc', sa.Text(), nullable=False),
    sa.Column('typ', sa.String(length=20), nullable=False),
    sa.Column('modul', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='nowa', nullable=False),
    sa.Column('autor_id', sa.BigInteger(), nullable=False),
    sa.Column('utworzono', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('zmieniono', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('nowa', 'w_realizacji', 'zrobiona', 'odrzucona')", name=op.f('ck_uwaga_status')),
    sa.CheckConstraint("typ IN ('poprawka', 'pomysl', 'blad')", name=op.f('ck_uwaga_typ')),
    sa.CheckConstraint('length(trim(tresc)) > 0', name=op.f('ck_uwaga_tresc_niepusta')),
    sa.ForeignKeyConstraint(['autor_id'], ['uzytkownik.id'], name=op.f('fk_uwaga_autor_id_uzytkownik'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uwaga'))
    )
    op.create_index(op.f('ix_uwaga_status'), 'uwaga', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uwaga_status'), table_name='uwaga')
    op.drop_table('uwaga')
    # ### end Alembic commands ###
