"""ustawienia: firma, konta bankowe, stawki VAT (kody FA(3))

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 20:52:40.107595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firma',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('nazwa', sa.String(length=250), server_default='', nullable=False),
    sa.Column('nazwa_skrocona', sa.String(length=100), server_default='', nullable=False),
    sa.Column('nip', sa.String(length=10), server_default='', nullable=False),
    sa.Column('regon', sa.String(length=14), server_default='', nullable=False),
    sa.Column('adres_ulica', sa.String(length=200), server_default='', nullable=False),
    sa.Column('kod_pocztowy', sa.String(length=10), server_default='', nullable=False),
    sa.Column('miejscowosc', sa.String(length=100), server_default='', nullable=False),
    sa.Column('kraj', sa.String(length=2), server_default='PL', nullable=False),
    sa.Column('email', sa.String(length=254), server_default='', nullable=False),
    sa.Column('telefon', sa.String(length=30), server_default='', nullable=False),
    sa.Column('www', sa.String(length=200), server_default='', nullable=False),
    sa.Column('miejsce_wystawienia', sa.String(length=100), server_default='', nullable=False),
    sa.Column('termin_platnosci_dni', sa.Integer(), server_default='14', nullable=False),
    sa.Column('forma_platnosci', sa.String(length=20), server_default='przelew', nullable=False),
    sa.Column('wystawiajacy', sa.String(length=100), server_default='', nullable=False),
    sa.Column('uwagi_na_fakturze', sa.Text(), server_default='', nullable=False),
    sa.Column('zmieniono', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("forma_platnosci IN ('przelew', 'gotowka', 'karta', 'mobilna')", name=op.f('ck_firma_forma_platnosci')),
    sa.CheckConstraint('id = 1', name=op.f('ck_firma_jeden_wiersz')),
    sa.CheckConstraint('termin_platnosci_dni BETWEEN 0 AND 365', name=op.f('ck_firma_termin_platnosci')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firma'))
    )
    op.create_table('konto_bankowe',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.Column('numer', sa.String(length=34), nullable=False),
    sa.Column('bank', sa.String(length=100), server_default='', nullable=False),
    sa.Column('swift', sa.String(length=11), server_default='', nullable=False),
    sa.Column('waluta', sa.String(length=3), server_default='PLN', nullable=False),
    sa.Column('domyslne', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('aktywne', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('utworzono', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("waluta ~ '^[A-Z]{3}$'", name=op.f('ck_konto_bankowe_waluta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_konto_bankowe')),
    sa.UniqueConstraint('numer', name=op.f('uq_konto_bankowe_numer'))
    )
    op.create_index('uq_konto_bankowe_domyslne', 'konto_bankowe', ['waluta'], unique=True, postgresql_where=sa.text('domyslne'))
    stawka_vat = op.create_table('stawka_vat',
    sa.Column('kod', sa.String(length=10), nullable=False),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.Column('procent', sa.SmallInteger(), nullable=True),
    sa.Column('kolejnosc', sa.SmallInteger(), nullable=False),
    sa.Column('aktywna', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('domyslna', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('procent IS NULL OR procent BETWEEN 0 AND 100', name=op.f('ck_stawka_vat_procent')),
    sa.PrimaryKeyConstraint('kod', name=op.f('pk_stawka_vat'))
    )
    op.create_index('uq_stawka_vat_domyslna', 'stawka_vat', ['domyslna'], unique=True, postgresql_where=sa.text('domyslna'))
    # ### end Alembic commands ###

    # Stawki startowe. Kody = wartosci pola P_12 schemy FA(3) (KSeF), wiec trafia na fakture bez tlumaczenia.
    op.bulk_insert(stawka_vat, [
        {"kod": "23", "nazwa": "23% (podstawowa)", "procent": 23, "kolejnosc": 10, "aktywna": True, "domyslna": True},
        {"kod": "8", "nazwa": "8% (obniżona)", "procent": 8, "kolejnosc": 20, "aktywna": True, "domyslna": False},
        {"kod": "5", "nazwa": "5% (obniżona)", "procent": 5, "kolejnosc": 30, "aktywna": True, "domyslna": False},
        {"kod": "0 KR", "nazwa": "0% (sprzedaż krajowa)", "procent": 0, "kolejnosc": 40, "aktywna": False, "domyslna": False},
        {"kod": "0 WDT", "nazwa": "0% (WDT — dostawa wewnątrzwspólnotowa)", "procent": 0, "kolejnosc": 50, "aktywna": False, "domyslna": False},
        {"kod": "0 EX", "nazwa": "0% (eksport towarów)", "procent": 0, "kolejnosc": 60, "aktywna": False, "domyslna": False},
        {"kod": "zw", "nazwa": "zw (zwolnione z VAT)", "procent": None, "kolejnosc": 70, "aktywna": True, "domyslna": False},
        {"kod": "oo", "nazwa": "oo (odwrotne obciążenie)", "procent": None, "kolejnosc": 80, "aktywna": False, "domyslna": False},
        {"kod": "np I", "nazwa": "np (poza terytorium kraju)", "procent": None, "kolejnosc": 90, "aktywna": False, "domyslna": False},
        {"kod": "np II", "nazwa": "np (usługi art. 100 ust. 1 pkt 4)", "procent": None, "kolejnosc": 100, "aktywna": False, "domyslna": False},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_stawka_vat_domyslna', table_name='stawka_vat', postgresql_where=sa.text('domyslna'))
    op.drop_table('stawka_vat')
    op.drop_index('uq_konto_bankowe_domyslne', table_name='konto_bankowe', postgresql_where=sa.text('domyslne'))
    op.drop_table('konto_bankowe')
    op.drop_table('firma')
    # ### end Alembic commands ###
