"""kartoteki: kontrahenci, towary, pracownicy

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-08 19:02:29.338364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kontrahent',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('typ', sa.String(length=20), server_default='firma', nullable=False),
    sa.Column('nazwa', sa.String(length=250), nullable=False),
    sa.Column('nip', sa.String(length=10), server_default='', nullable=False),
    sa.Column('nr_vat_ue', sa.String(length=20), server_default='', nullable=False),
    sa.Column('regon', sa.String(length=14), server_default='', nullable=False),
    sa.Column('adres_ulica', sa.String(length=200), server_default='', nullable=False),
    sa.Column('kod_pocztowy', sa.String(length=10), server_default='', nullable=False),
    sa.Column('miejscowosc', sa.String(length=100), server_default='', nullable=False),
    sa.Column('kraj', sa.String(length=2), server_default='PL', nullable=False),
    sa.Column('email', sa.String(length=254), server_default='', nullable=False),
    sa.Column('telefon', sa.String(length=30), server_default='', nullable=False),
    sa.Column('jest_odbiorca', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('jest_dostawca', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('termin_platnosci_dni', sa.SmallInteger(), nullable=True),
    sa.Column('uwagi', sa.Text(), server_default='', nullable=False),
    sa.Column('aktywny', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('utworzono', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('zmieniono', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("typ IN ('firma', 'osoba_fizyczna')", name=op.f('ck_kontrahent_typ')),
    sa.CheckConstraint('jest_odbiorca OR jest_dostawca', name=op.f('ck_kontrahent_rola')),
    sa.CheckConstraint('length(trim(nazwa)) > 0', name=op.f('ck_kontrahent_nazwa_niepusta')),
    sa.CheckConstraint('termin_platnosci_dni IS NULL OR termin_platnosci_dni BETWEEN 0 AND 365', name=op.f('ck_kontrahent_termin_platnosci')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kontrahent'))
    )
    op.create_index(op.f('ix_kontrahent_aktywny'), 'kontrahent', ['aktywny'], unique=False)
    op.create_index('uq_kontrahent_nip', 'kontrahent', ['nip'], unique=True, postgresql_where=sa.text("nip <> ''"))
    op.create_table('pracownik',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('imie', sa.String(length=100), nullable=False),
    sa.Column('nazwisko', sa.String(length=100), nullable=False),
    sa.Column('stanowisko', sa.String(length=100), server_default='', nullable=False),
    sa.Column('email', sa.String(length=254), server_default='', nullable=False),
    sa.Column('telefon', sa.String(length=30), server_default='', nullable=False),
    sa.Column('data_zatrudnienia', sa.Date(), nullable=True),
    sa.Column('data_zwolnienia', sa.Date(), nullable=True),
    sa.Column('uwagi', sa.Text(), server_default='', nullable=False),
    sa.Column('aktywny', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('utworzono', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('zmieniono', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('data_zwolnienia IS NULL OR data_zatrudnienia IS NULL OR data_zwolnienia >= data_zatrudnienia', name=op.f('ck_pracownik_daty')),
    sa.CheckConstraint('length(trim(imie)) > 0 AND length(trim(nazwisko)) > 0', name=op.f('ck_pracownik_imie_nazwisko')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pracownik'))
    )
    op.create_index(op.f('ix_pracownik_aktywny'), 'pracownik', ['aktywny'], unique=False)
    op.create_table('towar',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('nazwa', sa.String(length=250), nullable=False),
    sa.Column('typ', sa.String(length=20), nullable=False),
    sa.Column('jm', sa.String(length=10), server_default='szt.', nullable=False),
    sa.Column('stawka_vat_kod', sa.String(length=10), nullable=False),
    sa.Column('gtu', sa.String(length=6), nullable=True),
    sa.Column('cena_sprzedazy_netto', sa.BigInteger(), nullable=True),
    sa.Column('ean', sa.String(length=14), server_default='', nullable=False),
    sa.Column('uwagi', sa.Text(), server_default='', nullable=False),
    sa.Column('aktywny', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('utworzono', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('zmieniono', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("gtu IS NULL OR gtu ~ '^GTU_(0[1-9]|1[0-3])$'", name=op.f('ck_towar_gtu')),
    sa.CheckConstraint("typ IN ('towar_handlowy', 'surowiec', 'wyrob_gotowy', 'usluga')", name=op.f('ck_towar_typ')),
    sa.CheckConstraint('cena_sprzedazy_netto IS NULL OR cena_sprzedazy_netto >= 0', name=op.f('ck_towar_cena')),
    sa.CheckConstraint('length(trim(nazwa)) > 0', name=op.f('ck_towar_nazwa_niepusta')),
    sa.CheckConstraint('length(trim(symbol)) > 0', name=op.f('ck_towar_symbol_niepusty')),
    sa.ForeignKeyConstraint(['stawka_vat_kod'], ['stawka_vat.kod'], name=op.f('fk_towar_stawka_vat_kod_stawka_vat'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_towar')),
    sa.UniqueConstraint('symbol', name=op.f('uq_towar_symbol'))
    )
    op.create_index(op.f('ix_towar_aktywny'), 'towar', ['aktywny'], unique=False)
    op.create_index(op.f('ix_towar_typ'), 'towar', ['typ'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_towar_typ'), table_name='towar')
    op.drop_index(op.f('ix_towar_aktywny'), table_name='towar')
    op.drop_table('towar')
    op.drop_index(op.f('ix_pracownik_aktywny'), table_name='pracownik')
    op.drop_table('pracownik')
    op.drop_index('uq_kontrahent_nip', table_name='kontrahent', postgresql_where=sa.text("nip <> ''"))
    op.drop_index(op.f('ix_kontrahent_aktywny'), table_name='kontrahent')
    op.drop_table('kontrahent')
    # ### end Alembic commands ###
