"""dokumenty: faktury sprzedazy, pozycje, sumy po stawkach

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-08 17:54:44.614991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dokument',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('typ', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='szkic', nullable=False),
    sa.Column('seria_id', sa.BigInteger(), nullable=True),
    sa.Column('numer', sa.String(length=60), nullable=True),
    sa.Column('numer_obcy', sa.String(length=60), server_default='', nullable=False),
    sa.Column('dokument_korygowany_id', sa.BigInteger(), nullable=True),
    sa.Column('data_wystawienia', sa.Date(), nullable=False),
    sa.Column('data_sprzedazy', sa.Date(), nullable=False),
    sa.Column('termin_platnosci', sa.Date(), nullable=True),
    sa.Column('forma_platnosci', sa.String(length=20), server_default='przelew', nullable=False),
    sa.Column('miejsce_wystawienia', sa.String(length=100), server_default='', nullable=False),
    sa.Column('waluta', sa.String(length=3), server_default='PLN', nullable=False),
    sa.Column('kontrahent_id', sa.BigInteger(), nullable=True),
    sa.Column('nabywca_nazwa', sa.String(length=250), server_default='', nullable=False),
    sa.Column('nabywca_nip', sa.String(length=10), server_default='', nullable=False),
    sa.Column('nabywca_nr_vat_ue', sa.String(length=20), server_default='', nullable=False),
    sa.Column('nabywca_adres_ulica', sa.String(length=200), server_default='', nullable=False),
    sa.Column('nabywca_kod_pocztowy', sa.String(length=10), server_default='', nullable=False),
    sa.Column('nabywca_miejscowosc', sa.String(length=100), server_default='', nullable=False),
    sa.Column('nabywca_kraj', sa.String(length=2), server_default='PL', nullable=False),
    sa.Column('sprzedawca', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('konto_bankowe_id', sa.BigInteger(), nullable=True),
    sa.Column('suma_netto', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('suma_vat', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('suma_brutto', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('wystawiajacy', sa.String(length=100), server_default='', nullable=False),
    sa.Column('uwagi', sa.Text(), server_default='', nullable=False),
    sa.Column('ksef_numer', sa.String(length=50), nullable=True),
    sa.Column('ksef_status', sa.String(length=20), nullable=True),
    sa.Column('ksef_xml', sa.Text(), nullable=True),
    sa.Column('ksef_upo', sa.Text(), nullable=True),
    sa.Column('utworzono', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utworzyl_id', sa.BigInteger(), nullable=True),
    sa.Column('zmieniono', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zatwierdzono', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zatwierdzil_id', sa.BigInteger(), nullable=True),
    sa.Column('anulowano', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulowal_id', sa.BigInteger(), nullable=True),
    sa.Column('przyczyna_anulowania', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint("forma_platnosci IN ('przelew', 'gotowka', 'karta', 'mobilna')", name=op.f('ck_dokument_forma_platnosci')),
    sa.CheckConstraint("status <> 'anulowany' OR anulowano IS NOT NULL", name=op.f('ck_dokument_anulowany_kompletny')),
    sa.CheckConstraint("status = 'szkic' OR (numer IS NOT NULL AND seria_id IS NOT NULL AND kontrahent_id IS NOT NULL AND sprzedawca IS NOT NULL AND zatwierdzono IS NOT NULL)", name=op.f('ck_dokument_zatwierdzony_kompletny')),
    sa.CheckConstraint("status IN ('szkic', 'zatwierdzony', 'anulowany')", name=op.f('ck_dokument_status')),
    sa.CheckConstraint("typ IN ('faktura_sprzedazy', 'korekta_sprzedazy', 'proforma', 'faktura_zakupu', 'faktura_kosztowa')", name=op.f('ck_dokument_typ')),
    sa.CheckConstraint("waluta ~ '^[A-Z]{3}$'", name=op.f('ck_dokument_waluta')),
    sa.CheckConstraint('suma_brutto = suma_netto + suma_vat', name=op.f('ck_dokument_suma_brutto')),
    sa.CheckConstraint('termin_platnosci IS NULL OR termin_platnosci >= data_wystawienia', name=op.f('ck_dokument_termin')),
    sa.ForeignKeyConstraint(['anulowal_id'], ['uzytkownik.id'], name=op.f('fk_dokument_anulowal_id_uzytkownik'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dokument_korygowany_id'], ['dokument.id'], name=op.f('fk_dokument_dokument_korygowany_id_dokument'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['konto_bankowe_id'], ['konto_bankowe.id'], name=op.f('fk_dokument_konto_bankowe_id_konto_bankowe'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kontrahent_id'], ['kontrahent.id'], name=op.f('fk_dokument_kontrahent_id_kontrahent'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seria_id'], ['seria_numeracji.id'], name=op.f('fk_dokument_seria_id_seria_numeracji'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['utworzyl_id'], ['uzytkownik.id'], name=op.f('fk_dokument_utworzyl_id_uzytkownik'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zatwierdzil_id'], ['uzytkownik.id'], name=op.f('fk_dokument_zatwierdzil_id_uzytkownik'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dokument'))
    )
    op.create_index(op.f('ix_dokument_kontrahent_id'), 'dokument', ['kontrahent_id'], unique=False)
    op.create_index(op.f('ix_dokument_status'), 'dokument', ['status'], unique=False)
    op.create_index('ix_dokument_typ_data', 'dokument', ['typ', 'data_wystawienia'], unique=False)
    op.create_index('uq_dokument_typ_numer', 'dokument', ['typ', 'numer'], unique=True, postgresql_where=sa.text('numer IS NOT NULL'))
    op.create_table('dokument_pozycja',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('dokument_id', sa.BigInteger(), nullable=False),
    sa.Column('lp', sa.SmallInteger(), nullable=False),
    sa.Column('towar_id', sa.BigInteger(), nullable=True),
    sa.Column('nazwa', sa.String(length=500), nullable=False),
    sa.Column('jm', sa.String(length=10), nullable=False),
    sa.Column('ilosc', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('cena_netto', sa.BigInteger(), nullable=False),
    sa.Column('stawka_vat_kod', sa.String(length=10), nullable=False),
    sa.Column('gtu', sa.String(length=6), nullable=True),
    sa.Column('wartosc_netto', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("gtu IS NULL OR gtu ~ '^GTU_(0[1-9]|1[0-3])$'", name=op.f('ck_dokument_pozycja_gtu')),
    sa.CheckConstraint('cena_netto >= 0', name=op.f('ck_dokument_pozycja_cena')),
    sa.CheckConstraint('ilosc <> 0', name=op.f('ck_dokument_pozycja_ilosc')),
    sa.CheckConstraint('length(trim(nazwa)) > 0', name=op.f('ck_dokument_pozycja_nazwa_niepusta')),
    sa.ForeignKeyConstraint(['dokument_id'], ['dokument.id'], name=op.f('fk_dokument_pozycja_dokument_id_dokument'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stawka_vat_kod'], ['stawka_vat.kod'], name=op.f('fk_dokument_pozycja_stawka_vat_kod_stawka_vat'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['towar_id'], ['towar.id'], name=op.f('fk_dokument_pozycja_towar_id_towar'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dokument_pozycja')),
    sa.UniqueConstraint('dokument_id', 'lp', name='uq_dokument_pozycja_lp')
    )
    op.create_index(op.f('ix_dokument_pozycja_dokument_id'), 'dokument_pozycja', ['dokument_id'], unique=False)
    op.create_index(op.f('ix_dokument_pozycja_towar_id'), 'dokument_pozycja', ['towar_id'], unique=False)
    op.create_table('dokument_stawka',
    sa.Column('dokument_id', sa.BigInteger(), nullable=False),
    sa.Column('stawka_vat_kod', sa.String(length=10), nullable=False),
    sa.Column('kolejnosc', sa.SmallInteger(), nullable=False),
    sa.Column('netto', sa.BigInteger(), nullable=False),
    sa.Column('vat', sa.BigInteger(), nullable=False),
    sa.Column('brutto', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('brutto = netto + vat', name=op.f('ck_dokument_stawka_brutto')),
    sa.ForeignKeyConstraint(['dokument_id'], ['dokument.id'], name=op.f('fk_dokument_stawka_dokument_id_dokument'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stawka_vat_kod'], ['stawka_vat.kod'], name=op.f('fk_dokument_stawka_stawka_vat_kod_stawka_vat'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dokument_id', 'stawka_vat_kod', name=op.f('pk_dokument_stawka'))
    )
    # ### end Alembic commands ###

    # NIEZMIENNIK pilnowany przez bazę (PLAN, sekcja 3, pkt 1): zatwierdzonego dokumentu nie da się zmienić
    # ani usunąć — nawet błędem w kodzie czy ręcznym UPDATE-em. Jedyne dozwolone przejście to
    # zatwierdzony → anulowany (numer zostaje zajęty) oraz uzupełnianie pól KSeF (faza 8).
    op.execute("""
        CREATE FUNCTION dokument_ochrona() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE
            wolne text[] := ARRAY['status', 'anulowano', 'anulowal_id', 'przyczyna_anulowania',
                                  'ksef_numer', 'ksef_status', 'ksef_xml', 'ksef_upo'];
        BEGIN
            IF TG_OP = 'DELETE' THEN
                IF OLD.status <> 'szkic' THEN
                    RAISE EXCEPTION 'dokument %: usuwać można tylko szkic (status: %)', OLD.numer, OLD.status
                        USING ERRCODE = 'insufficient_privilege';
                END IF;
                RETURN OLD;
            END IF;
            IF OLD.status = 'szkic' THEN
                RETURN NEW;
            END IF;
            IF NEW.status <> OLD.status AND NOT (OLD.status = 'zatwierdzony' AND NEW.status = 'anulowany') THEN
                RAISE EXCEPTION 'dokument %: niedozwolona zmiana statusu % -> %', OLD.numer, OLD.status, NEW.status
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF OLD.status = 'anulowany' AND (NEW.anulowano, NEW.anulowal_id, NEW.przyczyna_anulowania)
                    IS DISTINCT FROM (OLD.anulowano, OLD.anulowal_id, OLD.przyczyna_anulowania) THEN
                RAISE EXCEPTION 'dokument %: anulowanie jest ostateczne', OLD.numer
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF (to_jsonb(NEW) - wolne) IS DISTINCT FROM (to_jsonb(OLD) - wolne) THEN
                RAISE EXCEPTION 'dokument %: zatwierdzonego dokumentu nie wolno zmieniać - tylko korekta lub anulowanie', OLD.numer
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            RETURN NEW;
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER dokument_nienaruszalny
        BEFORE UPDATE OR DELETE ON dokument
        FOR EACH ROW EXECUTE FUNCTION dokument_ochrona()
    """)
    # Pozycje i sumy po stawkach można zmieniać tylko w szkicu. Gdy dokument jest właśnie usuwany
    # (kaskada ze szkicu), wiersza dokumentu już nie widać — wtedy przepuszczamy.
    op.execute("""
        CREATE FUNCTION dokument_czesc_ochrona() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE
            st text;
        BEGIN
            IF TG_OP IN ('UPDATE', 'DELETE') THEN
                SELECT status INTO st FROM dokument WHERE id = OLD.dokument_id;
                IF st IS NOT NULL AND st <> 'szkic' THEN
                    RAISE EXCEPTION '%: dokument % nie jest szkicem - pozycji nie wolno zmieniać', TG_TABLE_NAME, OLD.dokument_id
                        USING ERRCODE = 'insufficient_privilege';
                END IF;
            END IF;
            IF TG_OP IN ('INSERT', 'UPDATE') THEN
                SELECT status INTO st FROM dokument WHERE id = NEW.dokument_id;
                IF st IS NOT NULL AND st <> 'szkic' THEN
                    RAISE EXCEPTION '%: dokument % nie jest szkicem - pozycji nie wolno zmieniać', TG_TABLE_NAME, NEW.dokument_id
                        USING ERRCODE = 'insufficient_privilege';
                END IF;
                RETURN NEW;
            END IF;
            RETURN OLD;
        END;
        $$
    """)
    for tabela in ("dokument_pozycja", "dokument_stawka"):
        op.execute(f"""
            CREATE TRIGGER {tabela}_tylko_w_szkicu
            BEFORE INSERT OR UPDATE OR DELETE ON {tabela}
            FOR EACH ROW EXECUTE FUNCTION dokument_czesc_ochrona()
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela in ("dokument_pozycja", "dokument_stawka"):
        op.execute(f"DROP TRIGGER IF EXISTS {tabela}_tylko_w_szkicu ON {tabela}")
    op.execute("DROP TRIGGER IF EXISTS dokument_nienaruszalny ON dokument")
    op.execute("DROP FUNCTION IF EXISTS dokument_czesc_ochrona()")
    op.execute("DROP FUNCTION IF EXISTS dokument_ochrona()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dokument_stawka')
    op.drop_index(op.f('ix_dokument_pozycja_towar_id'), table_name='dokument_pozycja')
    op.drop_index(op.f('ix_dokument_pozycja_dokument_id'), table_name='dokument_pozycja')
    op.drop_table('dokument_pozycja')
    op.drop_index('uq_dokument_typ_numer', table_name='dokument', postgresql_where=sa.text('numer IS NOT NULL'))
    op.drop_index('ix_dokument_typ_data', table_name='dokument')
    op.drop_index(op.f('ix_dokument_status'), table_name='dokument')
    op.drop_index(op.f('ix_dokument_kontrahent_id'), table_name='dokument')
    op.drop_table('dokument')
    # ### end Alembic commands ###
